name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: /home/runner/work/demo/demo

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Get artifacts
        uses: actions/download-artifact@master
        with:
          name: demo
          path: /home/runner/work/demo/demo

      - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: gozeus/demo
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
